name = "minigui"
version = "0.1.2"
description = "Basic GUI library for Gleam (Win32/GTK) using a C port with precompiled binaries."
licences = ["MIT"]
repository = { type = "github", user = "Aztekode", repo = "minigui" }
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
